### PR TITLE
Adding ppc64le support

### PR DESCRIPTION
**Pull request by nagesh4193**
Added ppc64le power support to the travis.

### CODE REVIEW

**Comment by EmmanuelP** [comment]
Thanks.

**Comment by EmmanuelP** [comment]
Hi @nagesh4193 

Currently the travis pipeline fails on ppc64le. Would you mind to have a look at the failures and try to understand what goes wrong ?

**Comment by EmmanuelP** [comment]
The error was caused by the version requirements put on setuptools.

**Comment by nagesh4193** [comment]
Thank you. Even I was trying to debug the issue, but still havent found a solution.

**Pull request merged**
