### PR TITLE
Add GStreamer property to use asynchronous USB API

### LINKED ISSUE #595: Add GStreamer property for asynchronous USB mode
**Is your feature request related to a problem? Please describe.**
Currently, the USB mode (synchronous/asynchronous) cannot be set for the GStreamer element `aravissrc`.
Apparently, only the synchronous mode is used.

**Describe the solution you'd like**
An additional property of the GStreamer element. Suggestion: A boolean named `asynchronous_usb`

**Describe alternatives you've considered**
Setting the mode _via_ an environment variable might also work.

### PR DESCRIPTION
**Pull request by schaerfo**
Fixes #595

### CODE REVIEW

**Comment by EmmanuelP** [comment]
Hi @schaerfo 

Thanks for the merge request. I'd prefer if you convert the boolean property to an enum one, like what is done for exposure-auto, and rename usb-asynchronous to usb-mode. It would be more consistent with the tool parameters.

Do you think you can handle that ?

**Comment by schaerfo** [comment]
Sure, that should be possible. The enum values would be synchronous, asynchronous and default, like in `ArvUvUsbMode`?

**Comment by EmmanuelP** [comment]
> The enum values would be synchronous, asynchronous and default, like in ArvUvUsbMode?

Yes, `sync`,  `async` and `default` to be precise.

**Comment by schaerfo** [comment]
> > The enum values would be synchronous, asynchronous and default, like in ArvUvUsbMode?
> 
> Yes, `sync`, `async` and `default` to be precise.

In this case, wouldn't it make sense to just re-use this enum?

**Comment by EmmanuelP** [comment]
> In this case, wouldn't it make sense to just re-use this enum? Otherwise, we would have two separate enums with a similar purpose and the same values

Yes, same enum please.

Thanks.

**Comment by EmmanuelP** [comment]
I'm going to push your changes to master. Thanks a lot.

**Pull request closed without merging**
