### PR TITLE
retrieve timeouts, missing frames/packets and resend limits

### PR DESCRIPTION
**Pull request by spatel-cog**
I'd like more detailed stats to be available via the python interface. 
Please let me know if these changes are acceptable or whether the current get_statistics API should be modified to include additional stats. I didn't want to break older code hence the introduction of a new API.

### CODE REVIEW

**Comment by EmmanuelP** [comment]
Hi Sandip,

Thanks for the merge request.

As you have noted, the current implementation is not flexible and require an API change each time we want to add a new data. Also, some data only make sense for a given interface.

So I would propose the following API instead of adding another non extensible one:

guint arv_stream_get_n_infos (ArvStream *stream)

double arv_stream_get_float_info (ArvStream *stream, guint id)
gint64 arv_stream_get_integer_info (ArvStream *stream, guint id)

const char *arv_stream_get_info_name (ArvStream *stream, guint id)
double arv_stream_get_float_info_by_name (ArvStream *stream, const char *name)
gint64 arv_stream_get_integer_info_by_name (ArvStream *stream, const char *name)

May be a bit over engineered, but extensible, and give us the possibility to add framerate and bandwidth informations.

**Comment by EmmanuelP** [comment]
By the way, I have commited the CI fix. It is in master now.

Thanks.

**Comment by spatel-cog** [comment]
Hi Emanuel, 
Thanks for reviewing my change request. 
I like your idea of having APIs to read ArvStream specific values. This will go a long way to exposing the kind of information that higher level APIs would like to see. 
Let me know how I can help.

Regards,
Sandip Patel,
Cogniac Corporation,
160 West Santa Clara St., Suite 1575
San Jose CA 95113.

**Comment by EmmanuelP** [comment]
> Let me know how I can help.

Well, if you have the time and willingness, you may try to implement the proposed API.

**Comment by EmmanuelP** [comment]
I have implemented an extensible stream info API here: https://github.com/AravisProject/aravis/pull/523

It obsoletes this pull request. I'm therefore closing it.

Thanks.

**Pull request closed without merging**
