### PR TITLE
usb3vision: Introduce libusb asynchronous I/O

### PR DESCRIPTION
**Pull request by iitaku**
Hi,

I've done some preliminary work to merge the async branch into master.
This PR is based on @makelinux's [async-master branch](https://github.com/makelinux/aravis/tree/async-master) and some extra change was made.

- Merging the latest master branch
- Signal handling for graceful cancellation
- Creating libusb event thread for each ArvUVDevice 

I think we still need to consider about following items.

1. How can we provide options to switch sync/async API? (or only async API if there are no downside?) (@EmmanuelP)
2. Make sure reset_endpoint can work with async API (@makelinux )

I'm happy to hear feedback and keep working on it.

### CODE REVIEW

**Comment by iitaku** [comment]
It is working with the Basler camera.

```
$./src/arv-camera-test-0.8
Looking for the first available camera
vendor name            = Basler
model name             = daA1280-54uc
device serial number   = 22665164
image width            = 1280
image height           = 960
horizontal binning     = 1
vertical binning       = 1
exposure               = 100000 µs
gain                   = 18 dB
payload                = 2457600 bytes
  9 frames/s -    22.1 MiB/s
 10 frames/s -    24.6 MiB/s
 10 frames/s -    24.6 MiB/s
 10 frames/s -    24.6 MiB/s
 10 frames/s -    24.6 MiB/s
 10 frames/s -    24.6 MiB/s
^C 10 frames/s -    24.6 MiB/s
n_completed_buffers    = 69
n_failures             = 0
n_underruns            = 0
n_transferred_bytes    = 0
n_ignored_bytes        = 0

(arv-camera-test-0.8:82623): GLib-CRITICAL **: 02:10:04.464: g_thread_join: assertion 'thread' failed

```

**Comment by EmmanuelP** [comment]
Thanks @iitaku for bringing this work back to life.

> 1. How can we provide options to switch sync/async API? (or only async API if there are no downside?) (@EmmanuelP)

I think it will be better to keep the sync code around for a while, even if we make the async mode the default. In case of trouble, it will be easier to switch to the sync mode for comparison if it is just an option to set. as for the API, have a lookt at `arv_gv_device_set_packet_adjustment()`. Something like `arv_uv_device_set_usb_mode()` will do the job, with 2 possible modes, `ARV_UV_DEVICE_USB_MODE_SYNC` and `ARV_UV_DEVICE_USB_MODE_ASYNC`.

> 2. Make sure reset_endpoint can work with async API (@makelinux )

I have no idea about that.

I did not review the code, but I have seen these issues:

- at runtime, we get `GLib-CRITICAL **: 19:40:13.377: g_thread_join: assertion 'thread' failed` errors
- at compilation time, we have a `'arv_uv_stream_get_statistics' defined but not used` warning
- probably related, the bandwidth statistic as seen in the viewer is not updated. It constantly show `0 Mb/s`.

**Comment by makelinux** [comment]
> Make sure reset_endpoint can work with async API (@makelinux )

I already don't work on this project and don't have a camera to testing.  My test environment was Xavier and Basler.

**Comment by iitaku** [comment]
> I think it will be better to keep the sync code around for a while, even if we make the async mode the default. In case of trouble, it will be easier to switch to the sync mode for comparison if it is just an option to set. as for the API, have a lookt at `arv_gv_device_set_packet_adjustment()`. Something like `arv_uv_device_set_usb_mode()` will do the job, with 2 possible modes, `ARV_UV_DEVICE_USB_MODE_SYNC` and `ARV_UV_DEVICE_USB_MODE_ASYNC`.

I've added API to select usb device I/O mode in this [commit](https://github.com/AravisProject/aravis/pull/557/commits/1cf1cc504871e287ce9390c3d6107645e4c4c0c9).  
ARV_UV_USB_MODE_SYNC is used in default.

> * at runtime, we get `GLib-CRITICAL **: 19:40:13.377: g_thread_join: assertion 'thread' failed` errors
> * at compilation time, we have a `'arv_uv_stream_get_statistics' defined but not used` warning
> * probably related, the bandwidth statistic as seen in the viewer is not updated. It constantly show `0 Mb/s`.

I also fixed these issues in this [commit](https://github.com/AravisProject/aravis/pull/557/commits/02ddc3edadaaf13a01115d6ae37d7266cb5b3190).

**Comment by iitaku** [comment]
> > Make sure reset_endpoint can work with async API (@makelinux )
> 
> I already don't work on this project and don't have a camera to testing. My test environment was Xavier and Basler.

Thanks for replying!
I've confirmed reset_endpoint works fin on x86 + Basler camera but I will test on Jetson Xavier as well.

**Comment by EmmanuelP** [comment]
Thanks @iitaku 

There seems to be an issue with chunk support:

```
Sources/aravis/build on  iitaku-libusb-async-io [$!?] took 3s ❯ ./src/arv-test-0.8 
Found 2 devices
Testing 'Basler:acA1920-155um'
Genicam:Load                        SUCCESS 
Genicam:Schema                      SUCCESS Version check disabled
Properties:SensorSizeReadout        SUCCESS 
Properties:SensorSizeCheck          SUCCESS 1936x1216
Properties:GainReadout              SUCCESS 
Properties:ExposureTimeReadout      SUCCESS 
MultipleAcquisition:BufferCheck     SUCCESS 10/10
MultipleAcquisition:FrameRate       SUCCESS 10.00 Hz
SingleAcquisition:BufferCheck       SUCCESS 

** (arv-test-0.8:20580): CRITICAL **: 11:17:20.615: arv_buffer_get_chunk_data: assertion 'arv_buffer_has_chunks (buffer)' failed
Chunks:BufferCheck                  FAILURE [ArvGcPort::read] Chunk 0xdb1316c9 not found
SoftwareTrigger:BufferCheck         SUCCESS 5/5
Testing 'Point Grey Research:Blackfly S BFS-U3-13Y3C'
Genicam:Load                        SUCCESS 
Genicam:Schema                      SUCCESS Version check disabled
Properties:SensorSizeReadout        SUCCESS 
Properties:SensorSizeCheck          SUCCESS 1280x1024
Properties:GainReadout              SUCCESS 
Properties:ExposureTimeReadout      SUCCESS 
MultipleAcquisition:BufferCheck     SUCCESS 10/10
MultipleAcquisition:FrameRate       SUCCESS 10.00 Hz
SingleAcquisition:BufferCheck       SUCCESS 

** (arv-test-0.8:20580): CRITICAL **: 11:17:22.605: arv_buffer_get_chunk_data: assertion 'arv_buffer_has_chunks (buffer)' failed
Chunks:BufferCheck                  FAILURE [ArvGcPort::read] Chunk 0x05040004 not found
SoftwareTrigger:*                   IGNORED 
 Disable SoftwareTrigger. We get 'USB transfer error: LIBUSB_ERROR_TIMEOUT' on software trigger emission
```

There is some warnings that sounds worrying but perhaps are not:

```
[10:53:12.809] 🅳 stream-thread> Start async USB3Vision stream thread
[10:53:12.809] 🅳 stream-thread> leader_size = 56
[10:53:12.809] 🅳 stream-thread> payload_size = 1048576
[10:53:12.809] 🅳 stream-thread> trailer_size = 40
[10:53:12.809] 🅳 stream-thread> Stream buffer context not found for buffer 0x1705470, creating...
[10:53:12.809] 🅳 stream-thread> Stream buffer context not found for buffer 0x1705500, creating...
[10:53:12.817] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:12.917] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.017] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.117] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.217] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.317] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.417] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.517] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.617] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.717] 🅳 stream-thread> Total payload: 1310720 bytes
[10:53:13.718] 🆆 stream-thread> Leader transfer failed: transfer->status = 3
[10:53:13.718] 🆆 stream-thread> Payload transfer failed: transfer->status = 3
[10:53:13.718] 🆆 stream-thread> Payload transfer failed: transfer->status = 3
[10:53:13.718] 🆆 stream-thread> Trailer transfer failed: transfer->status = 3
[10:53:13.718] 🆆 stream-thread> Leader transfer failed: transfer->status = 3
[10:53:13.719] 🆆 stream-thread> Payload transfer failed: transfer->status = 3
[10:53:13.719] 🆆 stream-thread> Payload transfer failed: transfer->status = 3
[10:53:13.719] 🆆 stream-thread> Trailer transfer failed: transfer->status = 3
[10:53:13.719] 🅳 stream-thread> Stop USB3Vision stream thread
```

It would be nice if you could add an option to `arv-camera-test` and `arv-test` that allows to choose the usb mode, something like `--usb-mode=async | sync`. That would help testing.

Also, could you add an helper to the `ArvCamera` API that sets the usb mode, in the `arv_camera_uv_` style ?

**Comment by iitaku** [comment]
@EmmanuelP 

> There seems to be an issue with chunk support:

I do not have a camera device that supports chunks. 
Do you have any recommendations to run all test cases?

> It would be nice if you could add an option to arv-camera-test and arv-test that allows to choose the usb mode, something like --usb-mode=async | sync. That would help testing.
> 
> Also, could you add an helper to the ArvCamera API that sets the usb mode, in the arv_camera_uv_ style ?

I've implemented arv_camera_uv_ style API and options for arv-camera-test and arv-test, but I noticed usb_mode should be determined beforehand creating camera object because thread callback function should be determined at ArvUvStream construction.

Do you have any suggestions on how can I pass this kind of option?

**Comment by EmmanuelP** [comment]
Hi,

> > There seems to be an issue with chunk support:
> 
> I do not have a camera device that supports chunks.

Don't worry, I'll have a look.

> Do you have any recommendations to run all test cases?

The meson tests are run using `ninja test`. There is also the `arv-test` application that exercises most of the functionalities of every connected cameras.

You may also run the tests under `valgrind`, using the `vagrind-memcheck` helper in tests. From the build directory, just run:

```
../tests/valgrind-memcheck
```
 
> > It would be nice if you could add an option to arv-camera-test and arv-test that allows to choose the usb mode, something like --usb-mode=async | sync. That would help testing.
> > Also, could you add an helper to the ArvCamera API that sets the usb mode, in the arv_camera_uv_ style ?
> 
> I've implemented arv_camera_uv_ style API and options for arv-camera-test and arv-test, but I noticed usb_mode should be determined beforehand creating camera object because thread callback function should be determined at ArvUvStream construction.
> 
> Do you have any suggestions on how can I pass this kind of option?

I don't understand. Could you explain a bit the issue you are facing ?

**Comment by iitaku** [comment]
>> I've implemented arv_camera_uv_ style API and options for arv-camera-test and arv-test, but I noticed usb_mode should be determined beforehand creating camera object because thread callback function should be determined at ArvUvStream construction.
>> 
>> Do you have any suggestions on how can I pass this kind of option?
>> 
> I don't understand. Could you explain a bit the issue you are facing ?

Current implementation should determine USB device I/O mode (async or sync) at  ArvUvStream construction and that will be triggered by calling `arv_camera_new`.  
That means, we need to set usb_mode prior to call `arv_camera_new` even if `arv_camera_uv_` style API takes `ArvCamera*` as first argument.

I think there are two options.

1. Modify ArvUvStream that can be able to switch usb_mode after it is constructed. (It may internally call arv_stream_stop_thread and arv_uv_stream_start_thread)
2. Provide another API to set usb_mode that can be called without ArvCamera* device.

**Comment by EmmanuelP** [comment]
> > > I've implemented arv_camera_uv_ style API and options for arv-camera-test and arv-test, but I noticed usb_mode should be determined beforehand creating camera object because thread callback function should be determined at ArvUvStream construction.
> > > Do you have any suggestions on how can I pass this kind of option?
> > 
> > 
> > I don't understand. Could you explain a bit the issue you are facing ?
> 
> Current implementation should determine USB device I/O mode (async or sync) at ArvUvStream construction and that will be triggered by calling `arv_camera_new`.
> That means, we need to set usb_mode prior to call `arv_camera_new` even if `arv_camera_uv_` style API takes `ArvCamera*` as first argument.
> 
> I think there are two options.
> 
>     1. Modify ArvUvStream that can be able to switch usb_mode after it is constructed. (It may internally call arv_stream_stop_thread and arv_uv_stream_start_thread)
> 
>     2. Provide another API to set usb_mode that can be called without ArvCamera* device.

In your code, you call `arv_u_stream_new` with `usb_mode` as a parameter. `priv->usb_mode` should be set to the correct value in the `constucted` method (no need to retrieve it using `g_object_get` by the way), as the `usb-mode` property is declared as CONSTRUCT_ONLY. As the thread is started at the end of `constructed`, it should use the correct usb mode.

**Comment by iitaku** [comment]
> That means we need to determine usb_mode when arv_camera_new is called.
> So just providing the arv_camera_uv* style API for usb_mode doesn't make sense because it is intended to be called after calling arv_camera_new.

Sorry, that is my misunderstanding.
Just never mind about this.

I've fixed some bugs. Can you please test it at your side? @EmmanuelP

**Comment by EmmanuelP** [comment]
Thanks @makelinux @iitaku 

The chunk fix was quite simple.

I have pushed your changes to master, with some minor cosmetic fixes, like ArvUvUsbMode instead of ArvUvUSBMode for consistency with other name with acronyms.

There is still 2, also minor, worries:

At the end of the streaming, there are some warnings about failed transfers:

```
[10:07:08.995] 🆆 stream-thread> Leader transfer failed: transfer->status = 3
[10:07:08.995] 🆆 stream-thread> Payload transfer failed: transfer->status = 3
[10:07:08.996] 🆆 stream-thread> Payload transfer failed: transfer->status = 3
```
I guess they could be avoided by checking the streaming is ending.

And a libusb event thread is created inconditionaly. Is this thread needed in case of synchronous libusb use ? If not, we should not create it.

**Comment by iitaku** [comment]
@EmmanuelP Thanks for merging this into master. I will keep eyes on the point you have mentioned make some time to investigate it.

**Comment by EmmanuelP** [comment]
I have created a set of new issues to track the last bits to fix:

https://github.com/AravisProject/aravis/issues/568
https://github.com/AravisProject/aravis/issues/569
https://github.com/AravisProject/aravis/issues/570

I'm closing this merge request.

**Pull request closed without merging**
