### PR TITLE
Broadcast discovery packets on all interfaces

### PR DESCRIPTION
**Pull request by highperformancecoder**
This appeared to be necessary for some Gev cameras implemented using the Pleora library, in that they ignored discovery packets transmitted on the global broadcast address.

### CODE REVIEW

**Comment by highperformancecoder** [comment]
@EmmanuelP Re building a list of broadcast addresses, I'm not familiar enough with gtk's data structures to be able to do this efficiently. GTK is not C nor C++. Sorry. We will need to continue using a forked version of the Aravis library until this functionality is implemented in the main branch.

**Comment by eudoxos** [comment]
@highperformancecoder does #547 work for you, could you test? Each interface uses its own broadcast address for sending packet discovery.
```
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 127.0.0.1 (127.0.0.1)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 169.254.21.100 (169.254.255.255)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 192.168.2.190 (192.168.2.255)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 192.168.122.1 (192.168.122.255)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 192.168.250.1 (192.168.250.1)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.18.0.1 (172.18.255.255)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.20.0.1 (172.20.255.255)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.19.0.1 (172.19.255.255)
[21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.17.0.1 (172.17.255.255)
```

**Comment by highperformancecoder** [comment]
> @highperformancecoder does #547 work for you, could you test? Each interface uses its own broadcast address for sending packet discovery.
> 
> ```
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 127.0.0.1 (127.0.0.1)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 169.254.21.100 (169.254.255.255)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 192.168.2.190 (192.168.2.255)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 192.168.122.1 (192.168.122.255)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 192.168.250.1 (192.168.250.1)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.18.0.1 (172.18.255.255)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.20.0.1 (172.20.255.255)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.19.0.1 (172.19.255.255)
> [21:41:32.212] 🅸 interface> [GvDiscoverSocket::new] Add interface 172.17.0.1 (172.17.255.255)
> ```

I don't know that we'll be able to test. We're currently in a city-wide lockdown, and the equipment is located in a facility on the other side of the city, which nobody can legally visit right now. At the rate this retched delta variant is going, I'll be leaving this job before the lockdown is lifted.

But I will look at the code, and try to remember what the problem was that this PR originally addressed.

**Comment by EmmanuelP** [comment]
I have reverted the code to use local broadcast address (255.255.255.255), and only use the interface broadcast address if the discovery packet can not be sent.

I could have let Aravis send discovery packets to both broadcast addresses, but I don't like the duplication. May be we could introduce an option to send to both addresses.

**Pull request closed without merging**
