### PR TITLE
Fixed #627: _send_cmd_and_receive_ack refactor

### LINKED ISSUE #627: Failed to connect to camera
**Describe the bug**
Aravis finds the camera but unable to connect.
I ran arv-camera-test with debug option.
```
pi@raspberrypi:~/aravis-0.8.20/build/src $ ./arv-camera-test-0.8 --debug=all
Looking for the first available camera
[16:05:40.361] 🅸 interface> Found 0 USB3Vision device (among 6 USB devices)
[16:05:40.363] 🅸 interface> [GvDiscoverSocket::new] Add interface 127.0.0.1 (127.0.0.1)
[16:05:40.364] 🅸 interface> [GvDiscoverSocket::new] Add interface 10.0.0.64 (10.255.255.255)
[16:05:40.369] 🅸 interface> [GvInterface::discovery] Device 'GigECamSim-6b:6e:05:05:22:c1' found (interface 10.0.0.64) user_id '' - MAC '6b:6e:05:05:22:c1'
[16:05:40.370] 🅸 device> [GvDevice::new] Interface address = 10.0.0.64
[16:05:40.370] 🅸 device> [GvDevice::new] Device address = 10.0.0.22
[16:05:40.871] 🆆 device> [GvDevice::read_memory] Ack reception timeout
[16:05:40.872] 🆆 device> [GvDevice::read_memory] Ack reception timeout
[16:05:40.873] 🅸 device> [GvDevice::load_genicam] xml url = 'Local:gigecamsim.xml; F000; 2B39' at 0x200
[16:05:40.873] 🅸 device> [GvDevice::load_genicam] Xml address = 0xf000 - size = 0x2b39 - gigecamsim.xml
[16:05:40.891] 🅸 genicam> [Gc::set_default_node_data] Add 'DeviceVendorName'
[16:05:40.892] 🅸 genicam> [Gc::set_default_node_data] Add 'DeviceModelName'
[16:05:40.892] 🅸 genicam> [Gc::set_default_node_data] Add 'DeviceVersion'
[16:05:40.893] 🅸 genicam> [Gc::set_default_node_data] Add 'DeviceManufacturerInfo'
[16:05:40.894] 🅸 genicam> [Gc::set_default_node_data] Add 'DeviceID'
[16:05:40.894] 🅸 genicam> [Gc::set_default_node_data] Add 'GevStreamChannelCount'
[16:05:40.895] 🅸 genicam> [Gc::set_default_node_data] Add 'GevSCPHostPort'
[16:05:40.896] 🅸 genicam> [Gc::set_default_node_data] Add 'GevSCPSDoNotFragment'
[16:05:40.897] 🅸 genicam> [Gc::set_default_node_data] Add 'GevSCPSBigEndian'
[16:05:40.898] 🅸 genicam> [Gc::set_default_node_data] Add 'GevSCDA'
[16:05:40.901] 🅸 genicam> [Gc::set_default_node_data] Add 'GevSCSP'
[16:05:40.902] 🅸 genicam> [Gc::set_default_node_data] Add 'GevSCPAddrCalc'
[16:05:41.403] 🆆 device> [GvDevice::write_register] Ack reception timeout
[16:05:41.403] 🆆 device> [GvDevice::write_register] Ack reception timeout
[16:05:41.406] 🆆 device> [GvDevice::take_control] Can't get control access
[16:05:41.407] 🅸 device> [GvDevice::new] Device endianness = little
[16:05:41.407] 🅸 device> [GvDevice::new] Packet resend     = no
[16:05:41.407] 🅸 device> [GvDevice::new] Write memory      = yes
[16:05:41.407] 🅸 device> [GvDevice::new] Legacy endianness handling = yes
Failed to read the current device configuration: GigEVision read_memory error (invalid-access)
[16:05:41.409] 🆆 device> [GvDevice::leave_control] Can't relinquish control access
```
**Platform description:**
 - Aravis version 8.20
 - OS: Raspbian 64bit, Ubuntu 20.04 64bit
 - Hardware: RaspberryPi4

What seems to be the problem?

Thanks,
Shorlak

### PR DESCRIPTION
**Pull request by adrianca88**
Related with #627 

Tested and working with SONY XCG-510C

Example:

image

### CODE REVIEW

**Comment by EmmanuelP** [comment]
Hi,

I'm not conviced by your patch. If we receive an error packet that matches the command and the packet id, there is no reason to retry, except may be if the error is ARV_GVCP_ERROR_BUSY (but in this case, we should receive a pending ack instead).

In your example, the error code is bad-alignment. Why would the command become sucessful after a retry ?

**Comment by adrianca88** [comment]
> In your example, the error code is bad-alignment. Why would the command become sucessful after a retry ?

This is the situation that we are getting now. Although the first attempt fails with bad-alignment error, it works the second time (as you can see on error log). 

We are getting this error randomly on different cameras (we have 16 cameras connected) and everything seems to be ok after review all network configuration params. We only have problems (sometimes) during camera connection, everything is ok on runtime while getting images.

Any suggestion or idea?

**Comment by adrianca88** [comment]
> > we have 16 cameras connected
> 
> Same or different cameras ? Could you tell the manufacturer and model you are using ?

Same cameras, SONY XCG 510C. 

We didn't have problems with aravis 0.5.13, but we are getting this error after upgrade to 0.8.19

**Comment by EmmanuelP** [comment]
> Same cameras, SONY XCG 510C.

I would suggest to report this issue to the manufacturer.

> We didn't have problems with aravis 0.5.13, but we are getting this error after upgrade to 0.8.19

If I recall correctly, errors were not handled at all in aravis 0.5.x.

As it does not look nice to always retry on error, a proper solution to your issue would be to add a `flags` property to ArvGvDevice, with one flag being `force-retry-on-error`, and use this flag in `_send_cmd_and_receive_ack`.

**Comment by adrianca88** [comment]
> As it does not look nice to always retry on error, a proper solution to your issue would be to add a flags property to ArvGvDevice, with one flag being force-retry-on-error, and use this flag in _send_cmd_and_receive_ack.

Yes, a new flag to choose this functionality seems to be a good solution. However, our error appears when calling to `arv_camera_new`, before the ArvDevice* is created. How can we add this flag?

**Comment by EmmanuelP** [comment]
I guess we have to introduce new functions: `arv_camera_new_with_flags()` and `arv_device_new_with_flags()`.

flags being a 32 bit integer, with the first 16 bits reserved for the generic flags, and the last 16 for the protocol specific flags.

**Pull request closed without merging**
