### PR TITLE
Fix fast-heartbeat meson build option

### PR DESCRIPTION
**Pull request by casperroo**
the meson did set up @ARAVIS_HAS_FAST_HEARTBEAT@ variable but it was not handled in the src/arvfeatures.h.in

Fix the issue with fast-heartbit meson option desribed in issue #392

### CODE REVIEW

**Comment by EmmanuelP** [comment]
I went for a simplified version of your patch.

Thanks.

**Comment by casperroo** [comment]
Looks ckeaner bu doesn't it brake backward compatibility with 0.6?
And in an ugly way: if one relied in his/her code on #ifdef
ARAVIS_FAST_HEARTBEAT he/she won't get any warning while porting to 0.8.
Or do I get it wrong?

Chris

czw., 30 lip 2020, 11:21 użytkownik Emmanuel Pacaud <
notifications@github.com> napisał:

**Comment by EmmanuelP** [comment]
I did not think about this potential issue, as I think the define is pretty useless outside of aravis compilation. But anyway, the define was not public in 0.6

**Comment by casperroo** [comment]
It was not indeed. Thanks for checking.

**Pull request closed without merging**
