### PR TITLE
Print number of detected devices in arv-tool

### PR DESCRIPTION
**Pull request by abrock**
I sometimes have 18 cameras connected and sometimes one is not responding. In this case it's very useful to immediately get the number of responding cameras.

### CODE REVIEW

**Comment by EmmanuelP** [comment]
Hi,

Thanks for the pull request. I'm not a huge fan of this additional line, especially now the complete list is displayed instantly when no action is required.

`arv-tool-0.8 | wc -l` should give you the number of found devices.

**Comment by abrock** [comment]
I like to see an overview of the cameras, so using | wc -l would require me to run arv-tool twice.

**Comment by EmmanuelP** [comment]
`arv-tool-0.8 | cat -n` ?

**Comment by abrock** [comment]
That's very cool, I didn't know that flag, thank you.

**Pull request closed without merging**
