### PR TITLE
Make ARV_PIXEL_FORMAT_CUSTOM_* unsigned integers

### PR DESCRIPTION
**Pull request by Ekleog**
This way the `.gir` file will get generated with the proper type.

See also https://github.com/gtk-rs/gir/issues/850 for more context.

Note that this isn't tested, I just submitted here what was suggested over at https://github.com/gtk-rs/gir/issues/850#issuecomment-543042780 in order to get feedback from your side too.

### CODE REVIEW

**Comment by EmmanuelP** [comment]
Thanks.

**Comment by EmmanuelP** [comment]
Unfortunately, it doesn't seem to fix the issue, gir data is the same:

```
    <constant name="PIXEL_FORMAT_CUSTOM_BAYER_BG_12_PACKED"
              value="2165047300"
              c:type="ARV_PIXEL_FORMAT_CUSTOM_BAYER_BG_12_PACKED">
      <source-position filename="../src/arvenums.h" line="178"/>
      <type name="gint" c:type="gint"/>
    </constant>
```

**Comment by EmmanuelP** [comment]
@Ekleog , by the way, is your work on aravis rust binding publicly available ?

**Comment by sdroege** [comment]
Something like this will likely be needed in addition

```c
/**
 * ARV_PIXEL_FORMAT_CUSTOM_BAYER_GR_12_PACKED: (value 2165047297) (type guint32)
 *
 * Blablablabla
 */
#define ARV_PIXEL_FORMAT_CUSTOM_BAYER_GR_12_PACKED  	0x810c0001u
```

The `value` annotation might be possible to skip in this case

**Comment by EmmanuelP** [comment]
Hi @sdroege ,

Thansk for the suggestion. Unfortunately, it doesn't seem to change the generated Gir file:

```C
/**
 * ARV_PIXEL_FORMAT_CUSTOM_BAYER_GR_12_PACKED: (value 2165047297) (type guint32)
 *
 * Packed bayer GR12 pixel format
 **/

#define ARV_PIXEL_FORMAT_CUSTOM_BAYER_GR_12_PACKED  	0x810c0001u
```
gives:
```xml
    <constant name="PIXEL_FORMAT_CUSTOM_BAYER_GR_12_PACKED"
              value="2165047297"
              c:type="ARV_PIXEL_FORMAT_CUSTOM_BAYER_GR_12_PACKED">
      <doc xml:space="preserve"
           filename="../src/arvenums.h"
           line="175">Packed bayer GR12 pixel format</doc>
      <source-position filename="../src/arvenums.h" line="181"/>
      <type name="gint" c:type="gint"/>
    </constant>
```

**Comment by sdroege** [comment]
Curious, we're using that in GStreamer for similar cases: https://gitlab.freedesktop.org/gstreamer/gstreamer/blob/487a3f9a30be15c72a98ca6cd744efb9c3d9a68e/gst/gstclock.h#L68-72

**Comment by sdroege** [comment]
Needs someone to understand how gobject-introspection does these things. In theory and according to the docs, that change above should work.

**Comment by EmmanuelP** [comment]
Thanks sebastien. I was playing with buidling gstreamer and indeed the gir file is correctly populated. I'm going to open an issue on gobject-introspection gitlab.

**Comment by sdroege** [comment]
Is it maybe because you closed the doc comment with ` **/` instead of ` */`? Would be silly if that's it but who knows...

Can you link the gobject-introspection issue you opened here?

**Comment by EmmanuelP** [comment]
> Is it maybe because you closed the doc comment with **/ instead of */? Would be silly if that's it but who knows...

It doesn't change anything.

> Can you link the gobject-introspection issue you opened here?

https://gitlab.gnome.org/GNOME/gobject-introspection/issues/315

**Comment by EmmanuelP** [comment]
The issue is fixed by this commit: a76541c0fe9a4b50eee1558020cc0ee36d95aaf4

**Pull request merged**
