### PR TITLE
gigevision: add APIs for GigE Vision IP setting

### LINKED ISSUE #479: Add an API for GigEVision IP settings
We should add an API to manage the IP settings of GigEVision devices.

Here is an example on how to set a persistent IP address: https://aravis-project.discourse.group/t/is-it-possible-to-change-the-ip-of-a-connected-camera/226/3

Without the API, user has to convert the IP address and mask to an integer value. Also we need to add GigEVision standard feature for IP settings (GevPersistentIPAddress, GevPersistentSubnetMask, GevPersistentDefaultGateway, GevCurrentIPConfigurationDHCP, GevCurrentIPConfigurationPersistentIP, GevCurrentIPConfigurationLLA) in the Genicam data if they are not resent in device XML.

The API would be:

```c
arv_camera_gv_set_persistent_ip_from_string (ArvCamera *camera, const char *ip, const char *mask, const char *gateway);
arv_camera_gv_set_persistent_ip (ArvCamera *camera, GInetAddress *ip, GInetAddressMask *mask, GInetAddress *gateway);
arv_camera_gv_set_ip_configuration_mode (ArvCamera *camera, ArvIPMode mode);
```

### PR DESCRIPTION
**Pull request by mshr-h**
This pull request adds some APIs for GigE Vision IP setting.

Fix #479

### CODE REVIEW

**Review by EmmanuelP — CHANGES_REQUESTED** [review]
Hi,

Thanks a lot for your work. There some trivial things to fix before the merge.

Not a requirement, but it would be nice to have a small command line tool that configures the IP settings of a camera.

Thanks again.

**Comment by mshr-h** [comment]
@EmmanuelP 
Thank you for your feedback. I've updated the code.
Can you take a look at it again?

**Review by EmmanuelP — CHANGES_REQUESTED** [review]

**Comment by mshr-h** [comment]
@EmmanuelP 
Thanks a lot! I've updated the code again.
Can you take a look at it?

**Comment by EmmanuelP** [comment]
Thanks a lot.

**Pull request merged**
