### PR TITLE
Create Usb device by name "Manufacturer;Product;Serial"

### PR DESCRIPTION
**Pull request by thecaptury**
this is similar to the gige method that can instantiate by IP address.

### CODE REVIEW

**Comment by thecaptury** [comment]
The thing is that I want to avoid using arv_update_device_list() because it is slow for GigE and I want to use DHCP if possible anyway. Using the device serial number is acceptable but I think it makes sense to check again whether the device is there now. So an alternative implementation would look something like this:

```
if (device_infos == NULL) {
    GList *device_list;

    _discover(uv_interface, uv_interface->priv->device_ids);
    device_infos = g_hash_table_lookup (uv_interface->priv->devices, device_id);
    if (device_infos == NULL)
        return NULL;
}
```

**Comment by EmmanuelP** [comment]
arv_uv_interface_open_device  already calls _discover. What would your alternative implementation add to the existing code ?

**Comment by thecaptury** [comment]
Ok. You are right, using "Manufacturer-Serial" works. reject this pull request please.

thanks.

**Comment by EmmanuelP** [comment]
Ok.

Regarding GigEvision, I have just pushed a patch that makes opening a device faster. The one second delay is gone.

**Pull request closed without merging**
